name: staging

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Building PKID for Production
        run: docker build . -t jimber/pkid:staging-${{ github.sha }}
      - name: Push the Docker image
        run: docker push jimber/pkid:staging-${{ github.sha }}

  deploy:
    needs: build
    runs-on: jimber-staging-server
    env:
      PKID_IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Down
        run: docker-compose -f docker-compose.staging.yml down
      - name: Deploy
        run: docker-compose -f docker-compose.staging.yml up -d
